# Generated by Django 3.2.9 on 2021-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=6)),
                ('time', models.TextField()),
                ('img', models.ImageField(upload_to='data')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
